name: PR Control Bot

on:
  issue_comment:
    types: [created]

jobs:
  control-pr:
    if: github.event.issue.pull_request && github.event.comment.user.login == 'jun-kb'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Auto approve PR
        if: contains(github.event.comment.body, '/approve')
        uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto approved via /approve command"
          pull-request-number: ${{ github.event.issue.number }}
      - name: Merge PR
        if: contains(github.event.comment.body, '/approve')
        run: gh pr merge ${{ github.event.issue.number }} --squash --delete-branch
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Close PR
        if: contains(github.event.comment.body, '/reject')
        run: gh pr close ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ github.token }}
