name: PR Control Bot

on:
  issue_comment:
    types: [created]

jobs:
  control-pr:
    if: github.event.issue.pull_request && github.event.comment.user.login == 'jun-kb'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          if [[ "${{ github.event.comment.body }}" == *"/approve"* ]]; then
            gh pr review ${{ github.event.issue.number }} --approve
            gh pr merge ${{ github.event.issue.number }} --squash --delete-branch
          elif [[ "${{ github.event.comment.body }}" == *"/reject"* ]]; then
            gh pr close ${{ github.event.issue.number }}
          fi
        env:
          GH_TOKEN: ${{ github.token }}
